language: c

addons:
  apt:
    packages:
      - libasound2:i386
      - libcairo2:i386
      - libz1:i386
      - libbz2-1.0:i386
      - libssl1.0.0:i386
      - libfreetype6:i386

install: 
  - wget -O - get.pharo.org/61+vm | bash
  - ./scripts/install-packages.sh
  - ./scripts/disable-deprecation-warning.sh 

script:
  - ./pharo talents.image test --no-xterm --fail-on-failure "Talents-Tests" "TraitsV2-Tests"
